server.port=3000
spring.datasource.url=jdbc:postgresql://172.17.0.97:5432/chitchat
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.auth.jwt-secret=supersecretjwtkeyforlab6evaluation1234567890
app.encryption.secret-key=0123456789abcdef0123456789abcdef
app.encryption.key-encryption-key=fedcba9876543210fedcba9876543210
spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=update
